[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "a1e30cac6e4dce14d93c144ba47711cc754414f5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "98164934ce091be52b36026674f83b3a89875c9c531f8475ee669ec6bc585fb6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.0.0+0/HelloWorldFortran.v1.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "a4ef1e002dde19d389560d0abfef182efeef2539"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "4328a5238b05575d81eda7c5b34c2044cc2bbbabb2c7a2a761c8f882fbf11429"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.0.0+0/HelloWorldFortran.v1.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "2621058eba2f975fa6539b722bd77db39aacfac1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "3174451153fd4f25e6a5c72d9b56066d1a2210cb877b788ce7379314166c0bee"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.0.0+0/HelloWorldFortran.v1.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "0e514a9b3ff2c4ae0a05dd6fac4a22bb175b5029"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "8a25f231e3cbee608b8d7093a924e4634f5959c50f9682887fc39f04f5651724"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.0.0+0/HelloWorldFortran.v1.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "501babfb1859f10088b52150382be97877e08a07"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "6b0fb8971f409e5ad1e30e0d89ae52399b5b8d45e781731e9ebd5397169a5761"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.0.0+0/HelloWorldFortran.v1.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
