[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "4cd4f2ac735eaf6f3ba39b4cc6fe3a9bcb098594"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "c864eef082e75a4cbe51a7672efcf61da62b010ba4d013c97484f5464f5b76d9"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "aac01afd57628db5613728d56c01f54d6c5a5c06"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "58b5f7a4ff80ca74f1deedca2e566a492825e6a1c6fdc90c7bcebc03bf329639"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "c0418a3dc467f1d01b3650d32a16da419dd84733"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "f27d203a024cc60f645bd32fea5529847a470c4f80564f86e3b019d8b4dfef18"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "8840abcc4f52b1b5fbd09789cc1fc745914616f5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "6d82ee8b9e790ddf8dd5b9c7ed2e42f0aea8bc876559f4744263fb65846b87e2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "7f8e8b9516b0ea726fae9106a0a3731b370b34d4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "247dff9b1fbd87855585f7392c047537615359e17df0734673fd1f57ac6453a0"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "aarch64"
git-tree-sha1 = "c07a1200aad5f1ca578fdec2babd0e4e8d933537"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "a08fed123f844a1b8c47b05f33927ead24278168151fe1c4ccf5450c03344964"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a615791c757e51dac12dea99044f291cfcda30da"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "380ff0e965303f1e2ccdde2b0a84765c2784bf03228e03bec914d3110909d5d5"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3474df6dd8e35ed8859c278e6f051b0292b63dd6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "4db964365099bff576ad1c5672e3c6ca55761d1d7564b2c05013c6ff85fddf47"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc83ee8ade508c61cf8b78c97c658f271b9f161d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "9efdd8e95dca86c6df786c5fee38585e432046afcadaf088ce268da21f696a1f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b199c50b8d28b8e8aa7c044168ed654b1c36b1c9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "bf456832baac12cdec6829948065957f2589d59081dfec3cb8e9776dda827029"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af3407d14532d053ea3bbd44804ef2be4913cc1e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "8f972d4d8225674d923246c2bd119aa785f480b4e7f228054c931a1ee904dd23"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d438d312bb46ba03adec6b57eb45fd66878a7e58"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "4a0e1198fa504ec0835a889f43c40dc9c514b3c28acc0122411ba7dc4c4c57aa"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "037d859665718f7b8b208d1aef778a611aa4cd32"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "0cf0b29e08b17392f162fb0e1f8bd96347904870ca60db5e3a41f8887cefa63a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "3e932df656f0f5432cb397ab83a1c9a5e966060c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "7555a8cec4c1595bde39d32ba46b96ec2f8c3108db74fb5d7a0a80c5ac77cfb2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "d49d6ccc28c63696718732de41adec2bd96cadb1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "9ecc43df126838c5095608e79a39c00124c700541f2da473ddbe7b9754a1bc4a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "32c312e0caa34d634abb54d40296b4aa3c3bf42f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "bfd33c75dfa7db58c1e11eb9768360fe1d909352fdae0bab7deb94706909e5d9"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "2bf33f53718e4c1c9a9a936f56285ef45b3ada28"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "2ffa3a98b2bd5a3ba8147a6563531525e7dfdd03d11c675b93757d80aefddba6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "8fe30d790644dbdd251b2e1d2dcbd5e2c1346dd9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "c097cb5499cae8bb6a4e0750be701e51a594d65cd0ec5e1d486e08f86b961dd2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "5fc1934356374011e1cc88d74b268ffa2a9255cb"
libgfortran_version = "3.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "ea5c2309b0531c4ea1277d822b97d4c1512258c748e26d8a2fce20bf579a4b59"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "dbf68d96a68f57fff73f10a1ca2fd2f8b279ef97"
libgfortran_version = "4.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "f5698b81606ced6a3e4dd0a5e210f7a71b6898fb119b19b0f3ec0a6be84055be"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "i686"
git-tree-sha1 = "4ba113bc528adc32f0304680d8dd0ee90ac7b6c4"
libgfortran_version = "5.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "4ba57d3ea378c888cc388086db13784c599c3930199ae982e7afbe585d982226"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "powerpc64le"
git-tree-sha1 = "c90f5b709affe166a22486c4201ccaee9ab119d1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "b3e5625955235ec69adc5de945ad3bc445f4da9466210a479c877bf7bd4b64ea"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "powerpc64le"
git-tree-sha1 = "40246f121c32afe4983279590e0bd41c063e4980"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "c7da8071835568c77a0e39e85e318bf6bcc88bcaf596bb98f140a9450e68e879"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "powerpc64le"
git-tree-sha1 = "cfece2d0e44d3a1663f68d027e02458638cba3db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "f990b6f4e2b294f0300b80002132ae92e131e2a879080d48aa127bbce8110bf4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "83a4dfa610e07e3d76c77c4ae01de67923b5f5da"
libgfortran_version = "3.0.0"
os = "macos"

    [[HelloWorldFortran.download]]
    sha256 = "40d8f9abfe2ee6d0459033e4c8a8e1621f51214ccc0af433547dbcc3667ebfe1"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "68c61b9e1e2ac1d074a1aaed3076c43f2a58a7cf"
libgfortran_version = "4.0.0"
os = "macos"

    [[HelloWorldFortran.download]]
    sha256 = "62ef0f0f0f5393cb0858a08222ab8f0f41e6e756a87c5432e9056590ae6c4c01"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "aa093cc5c1bf06e8b8d51bcb4ea85a06eeb64c24"
libgfortran_version = "5.0.0"
os = "macos"

    [[HelloWorldFortran.download]]
    sha256 = "8da6abedcf026f72b13fa3da8e067ea4c1e8f5039bb685c2b8536aa75a846d9c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "31023558f3d7b4b436dccfbfe6219cb3de6fa8f7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "15b0ad7753a2849da20445cbb28488f68023664d430f07d5f4b0db529f9e566a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "dd2b261f792fdbee1827b1fc66e70a3e79fe9bc5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "40e5cf8294a9931297bee54c3b526f4535a42ede887a947f871e7f9471d7b975"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "f49d01301b3e5badf5ef841edc791498e4385a4a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "97ad4a23b0df215f2afb066a79fb02ebf23e0a5974fb6a67a7dd5db943fd2e42"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "1eb6f112f1cfa07cb65a755ec8e930ee5a3bed02"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "89fbf19bf37503191063f9df3f244ca9c9c62ad8250469f6b6328acd00b27498"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "3633ad7e0929706598b3f8fa3b4ef321de387296"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "91d697f541971885b514425e4f2b28c7a12e4e43971e7fd9fc7940597ab8de7a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "6902c392ae523c741e6bcdc7219bf049cb616498"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[HelloWorldFortran.download]]
    sha256 = "2e63d6c2a3b4b7c426ba0be7009ef41cebd2b19f561476e80e63dce3a2d57686"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "93e7a6ce57258bddea36bce39faea4df81d808f3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[HelloWorldFortran.download]]
    sha256 = "f997592dbfadcb58a7dcfa84a35cfebb16bd22bf1421306e2bf05e504ec23db0"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "39928324acd4dc586a664ef70bced10f77ab8746"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[HelloWorldFortran.download]]
    sha256 = "10abecf1384af38f78f6ff369ce219da8804620249ad24ffb15525d474ba290e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "79d8356c4fbdb623be6f8e53d14b538319ce6363"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[HelloWorldFortran.download]]
    sha256 = "4e007625015a1286ce4eb24e2ec68c4e75f0b04775f28dcc497cb5ccdb989048"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "a1a717257ad1d24319b981b4865758f75df8d2bf"
libgfortran_version = "3.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "46357205f0d8c6f499682cf88c6236ee0120b3fa7ae4731298e977a4f91540d4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "fdfc30938017f051ecb5976caccaac1f6d0b426d"
libgfortran_version = "4.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "604301e4d9dcefa6aa436993134833c2f73b8d6408400fa8de9bb55de6c65df6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[HelloWorldFortran]]
arch = "x86_64"
git-tree-sha1 = "5809330e1012eefae194643cf4a24e9e67e0181d"
libgfortran_version = "5.0.0"
os = "windows"

    [[HelloWorldFortran.download]]
    sha256 = "e178381abc367c7c69cb395246629509584a3cd08130fa6b734b3ebdd749e6dd"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldFortran_jll.jl/releases/download/HelloWorldFortran-v1.1.0+0/HelloWorldFortran.v1.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
